from setuptools import setup

setup(
    name='nlfte',
    version='',
    packages=['venv.lib.python2.7.distutils', 'venv.lib.python2.7.encodings', 'venv.lib.python2.7.site-packages.fte',
              'venv.lib.python2.7.site-packages.pip', 'venv.lib.python2.7.site-packages.pip._vendor',
              'venv.lib.python2.7.site-packages.pip._vendor.idna',
              'venv.lib.python2.7.site-packages.pip._vendor.pep517',
              'venv.lib.python2.7.site-packages.pip._vendor.pytoml',
              'venv.lib.python2.7.site-packages.pip._vendor.certifi',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet',
              'venv.lib.python2.7.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib',
              'venv.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python2.7.site-packages.pip._vendor.msgpack',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python2.7.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python2.7.site-packages.pip._vendor.colorama',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python2.7.site-packages.pip._vendor.lockfile',
              'venv.lib.python2.7.site-packages.pip._vendor.progress',
              'venv.lib.python2.7.site-packages.pip._vendor.requests',
              'venv.lib.python2.7.site-packages.pip._vendor.packaging',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python2.7.site-packages.pip._vendor.webencodings',
              'venv.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python2.7.site-packages.pip._internal', 'venv.lib.python2.7.site-packages.pip._internal.cli',
              'venv.lib.python2.7.site-packages.pip._internal.req',
              'venv.lib.python2.7.site-packages.pip._internal.vcs',
              'venv.lib.python2.7.site-packages.pip._internal.utils',
              'venv.lib.python2.7.site-packages.pip._internal.models',
              'venv.lib.python2.7.site-packages.pip._internal.commands',
              'venv.lib.python2.7.site-packages.pip._internal.operations', 'venv.lib.python2.7.site-packages.cffi',
              'venv.lib.python2.7.site-packages.numpy', 'venv.lib.python2.7.site-packages.numpy.ma',
              'venv.lib.python2.7.site-packages.numpy.ma.tests', 'venv.lib.python2.7.site-packages.numpy.doc',
              'venv.lib.python2.7.site-packages.numpy.fft', 'venv.lib.python2.7.site-packages.numpy.fft.tests',
              'venv.lib.python2.7.site-packages.numpy.lib', 'venv.lib.python2.7.site-packages.numpy.lib.tests',
              'venv.lib.python2.7.site-packages.numpy.core', 'venv.lib.python2.7.site-packages.numpy.core.tests',
              'venv.lib.python2.7.site-packages.numpy.f2py', 'venv.lib.python2.7.site-packages.numpy.f2py.tests',
              'venv.lib.python2.7.site-packages.numpy.tests', 'venv.lib.python2.7.site-packages.numpy.compat',
              'venv.lib.python2.7.site-packages.numpy.compat.tests', 'venv.lib.python2.7.site-packages.numpy.linalg',
              'venv.lib.python2.7.site-packages.numpy.linalg.tests', 'venv.lib.python2.7.site-packages.numpy.random',
              'venv.lib.python2.7.site-packages.numpy.random.tests', 'venv.lib.python2.7.site-packages.numpy.testing',
              'venv.lib.python2.7.site-packages.numpy.testing.tests',
              'venv.lib.python2.7.site-packages.numpy.testing._private',
              'venv.lib.python2.7.site-packages.numpy.distutils',
              'venv.lib.python2.7.site-packages.numpy.distutils.tests',
              'venv.lib.python2.7.site-packages.numpy.distutils.command',
              'venv.lib.python2.7.site-packages.numpy.distutils.fcompiler',
              'venv.lib.python2.7.site-packages.numpy.matrixlib',
              'venv.lib.python2.7.site-packages.numpy.matrixlib.tests',
              'venv.lib.python2.7.site-packages.numpy.polynomial',
              'venv.lib.python2.7.site-packages.numpy.polynomial.tests', 'venv.lib.python2.7.site-packages.wheel',
              'venv.lib.python2.7.site-packages.wheel.cli', 'venv.lib.python2.7.site-packages.Crypto',
              'venv.lib.python2.7.site-packages.Crypto.Hash', 'venv.lib.python2.7.site-packages.Crypto.Util',
              'venv.lib.python2.7.site-packages.Crypto.Cipher', 'venv.lib.python2.7.site-packages.Crypto.Random',
              'venv.lib.python2.7.site-packages.Crypto.Random.OSRNG',
              'venv.lib.python2.7.site-packages.Crypto.Random.Fortuna',
              'venv.lib.python2.7.site-packages.Crypto.Protocol', 'venv.lib.python2.7.site-packages.Crypto.SelfTest',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Hash',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Util',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Cipher',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Random',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Random.OSRNG',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Random.Fortuna',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Protocol',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.PublicKey',
              'venv.lib.python2.7.site-packages.Crypto.SelfTest.Signature',
              'venv.lib.python2.7.site-packages.Crypto.PublicKey', 'venv.lib.python2.7.site-packages.Crypto.Signature',
              'venv.lib.python2.7.site-packages.pycparser', 'venv.lib.python2.7.site-packages.pycparser.ply',
              'venv.lib.python2.7.site-packages.setuptools', 'venv.lib.python2.7.site-packages.setuptools.extern',
              'venv.lib.python2.7.site-packages.setuptools._vendor',
              'venv.lib.python2.7.site-packages.setuptools._vendor.packaging',
              'venv.lib.python2.7.site-packages.setuptools.command', 'venv.lib.python2.7.site-packages.pkg_resources',
              'venv.lib.python2.7.site-packages.pkg_resources.extern',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor',
              'venv.lib.python2.7.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='',
    author_email='',
    description='python library that provides the tools for obfuscating ciphers in the form of natural language and '
                'more specifically auxiliary verb sentences using ftelib by Dyer et al. '

)
